name: PayPaySampleCurrencyConverter
options:
  bundleIdPrefix: com.abc.abc
targets:
  PayPaySampleCurrencyConverter:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - PayPaySampleCurrencyConverter
